[package]
name = "mcp-database"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]

[dependencies]
diesel = { version = "^1.3", default-features = false, features = ["sqlite"] }
dotenv = "0.9.0"